# Generated by Django 5.2.3 on 2025-06-24 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('persona_a_visitar', models.CharField(max_length=100)),
                ('motivo_visita', models.TextField()),
                ('fecha_hora_llegada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('codigo_qr_usado', models.CharField(max_length=100)),
            ],
        ),
    ]
